server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3310/login?characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  logging:
    level:
      org.hibernate.sql: debug
      org.hibernate.type: info

